### PR TITLE
not all new items in a notification are getting recognized

### PR DESCRIPTION
**Pull request by mborho**
fixed with this commit

### CODE REVIEW

**Comment by superfeedr** [comment]
Looks great! Thanks... do you mind writing a quick test so we keep a good coverage? Thanks!

**Comment by mborho** [comment]
i could try, but i don't know how to mock such a notification. perhaps something like a "douple post" checkbox on http://push-pub.appspot.com/ ?

**Comment by superfeedr** [comment]
Martin,

I just added the option to generate double posts to http://push-pub.appspot.com/ :) Let me know what you think!

Thanks

**Comment by mborho** [comment]
Hi Julien,

have you seen the second commit with the test?

Martin

**Pull request merged**
